name: docker-build

on:
  push:
    branches-ignore:
    - "renovate/**"
    paths:
    - "ubuntu/22.04/**"
    - ".github/workflows/docker-build.yml"
  pull_request:
    types:
    - opened
    - synchronize
    - labeled
    - reopened
    paths:
    - "ubuntu/22.04/**"
    - ".github/workflows/docker-build.yml"
  workflow_dispatch:

jobs:
  build:
    name: docker-build
    permissions:
      packages: write
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: 22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      uses: docker/build-push-action@v4
      with:
        context: ubuntu/22.04
        platforms: linux/amd64
        provenance: false
        sbom: false
        cache-from: ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}
