name: docker-build

on:
  push:
    branches-ignore:
    - "renovate/**"
    paths:
    - "ubuntu/22.04/**"
    - ".github/workflows/docker-build.yml"
  pull_request:
    types:
    - opened
    - synchronize
    - labeled
    - reopened
    paths:
    - "ubuntu/22.04/**"
    - ".github/workflows/docker-build.yml"
  workflow_dispatch:

jobs:
  build:
    name: docker-build
    permissions:
      packages: write
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: 22.04
    steps:

    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@2b51285047da1547ffb1b2203d8be4c0af6b1f20 # v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v4
      with:
        context: ubuntu/22.04
        platforms: linux/amd64
        provenance: false
        sbom: false
        cache-from: ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}
